import type { Metadata } from "next";
import "./globals.css";
import { CookieConsent, Footer, Navbar, PreLoader } from "./_components";
import SmoothLayout from "./_components/smoothLayout";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-drak-body">
        {/* <PreLoader /> */}
        <SmoothLayout>
          <Navbar />
          <main>{children}</main>
          <CookieConsent />
          <Footer />
        </SmoothLayout>
      </body>
    </html>
  );
}
