import type { Metadata } from "next";
import "./globals.css";
import SmoothLayout from "./_components/smoothLayout";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <script src="https://dl.dropboxusercontent.com/s/f62j9uzlmzp1bnu/ScrollSmoother.min.js?raw=1"></script>
      </head>
      <body className="dark:bg-[#080808]">
        <SmoothLayout>{children}</SmoothLayout>
      </body>
    </html>
  );
}
